image: gcc

stages:
  - build

before_script:
  - apt-get update
  - apt-get -y install cmake
  - apt-get -y install libxcb-render0-dev libxcb-randr0-dev libxcb-util0-dev libxcb-cursor-dev libcairo2-dev libyaml-dev
  - apt-get -y install libudev-dev libjson-c-dev libmpdclient-dev libasound2-dev libxcb-xkb-dev

configure:
  stage: build
  script:
    - mkdir -p bld/debug
    - cd bld/debug
    - cmake -DCMAKE_BUILD_TYPE=Debug ../../

build:
  stage: build
  script:
    - cd bld/debug
    - make
