image: gcc

stages:
  - build

before_script:
    - apt-get update
    - apt-get -y install cmake xcb alsa-lib json-c libmpdclient

configure:
  stage: build
  script:
    - mkdir -p bld/debug
    - cd bld/debug
    - cmake -DCMAKE_BUILD_TYPE=Debug ../../

build:
  stage: build
  script:
    - cd bld/debug
    - make
