image: alpine:latest

stages:
  - build

before_script:
  - apk update
  - apk add musl-dev eudev-libs eudev-dev linux-headers cmake ninja gcc
  - apk add libxcb-dev xcb-util-wm-dev xcb-util-cursor-dev cairo-dev yaml-dev
  - apk add json-c-dev libmpdclient-dev alsa-lib-dev i3wm

debug:
  stage: build
  script:
    - mkdir -p bld/debug
    - cd bld/debug
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ../../
    - ninja

release:
  stage: build
  script:
    - mkdir -p bld/release
    - cd bld/release
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel ../../
    - ninja
