stages:
  - build

configure:
  stage: build
  script:
    - mkdir -p bld/debug
    - cd bld/debug
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ../../

build:
  stage: build
  script:
    - cd bld/debug
    - ninja
