image: alpine:edge

stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: normal

before_script:
  - echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
  - apk update
  - apk add musl-dev eudev-libs eudev-dev linux-headers meson ninja gcc scdoc
  - apk add libxcb-dev xcb-util-wm-dev xcb-util-cursor-dev cairo-dev yaml-dev
  - apk add wayland-dev wayland-protocols wlroots-dev
  - apk add json-c-dev libmpdclient-dev alsa-lib-dev

debug:
  stage: build
  script:
    - apk add gcovr
    - python2 -m ensurepip --upgrade
    - python2 -m pip install --upgrade pip
    - python2 -m pip install --upgrade setuptools
    - mkdir -p bld/debug
    - cd bld/debug
    - meson --buildtype=debug -Db_coverage=true ../..
    - ninja -k0
    - ninja test
    - cat /usr/bin/gcovr
    - python2 -m gcovr --version
    - gcovr --version
    - ninja coverage-xml

release:
  stage: build
  script:
    - mkdir -p bld/release
    - cd bld/release
    - meson --buildtype=minsize ../../
    - ninja -k0
    - ninja test

x11_only:
  stage: build
  script:
    - mkdir -p bld/debug
    - cd bld/debug
    - meson --buildtype=debug -Dbackend-x11=enabled -Dbackend-wayland=disabled ../../
    - ninja -k0
    - ninja test

wayland_only:
  stage: build
  script:
    - mkdir -p bld/debug
    - cd bld/debug
    - meson --buildtype=debug -Dbackend-x11=disabled -Dbackend-wayland=enabled ../../
    - ninja -k0
    - ninja test

plugins_as_shared_modules:
  stage: build
  script:
    - mkdir -p bld/debug
    - cd bld/debug
    - meson --buildtype=debug -Dcore-plugins-as-shared-libraries=true ../../
    - ninja -k0
    - ninja test
